// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhDPl9Kp4JcpZ-Y85yg8ImVllxFE9ffs',
    appId: '1:368981372884:web:b174e04864eaabc25ff041',
    messagingSenderId: '368981372884',
    projectId: 'flash-chat-30cc6',
    authDomain: 'flash-chat-30cc6.firebaseapp.com',
    storageBucket: 'flash-chat-30cc6.appspot.com',
    measurementId: 'G-BL945NGSWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAY3PlP-hscbdCjXcgzSfntiSEyNnt4Ng',
    appId: '1:368981372884:android:b275b617ac468d905ff041',
    messagingSenderId: '368981372884',
    projectId: 'flash-chat-30cc6',
    storageBucket: 'flash-chat-30cc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUPT_taESjvlOpZLEiHCFYIaJzbio4Uk',
    appId: '1:368981372884:ios:b92c0231f55af3145ff041',
    messagingSenderId: '368981372884',
    projectId: 'flash-chat-30cc6',
    storageBucket: 'flash-chat-30cc6.appspot.com',
    iosClientId: '368981372884-5dd1bahng29b0fh3r3sav1j2n9ftq0kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGameFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMUPT_taESjvlOpZLEiHCFYIaJzbio4Uk',
    appId: '1:368981372884:ios:b92c0231f55af3145ff041',
    messagingSenderId: '368981372884',
    projectId: 'flash-chat-30cc6',
    storageBucket: 'flash-chat-30cc6.appspot.com',
    iosClientId: '368981372884-5dd1bahng29b0fh3r3sav1j2n9ftq0kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGameFlutter',
  );
}
